export const GET_ALL_PROJECT_REQUEST = "GET_ALL_PROJECT_REQUEST";
export const GET_ALL_PROJECT_SUCCESS = "GET_ALL_PROJECT_SUCCESS";
export const GET_ALL_PROJECT_FAILURE = "GET_ALL_PROJECT_FAILURE";

export const CLEAR_MESSEAGE = "CLEAR_MESSEAGE";

export const DELETE_PROJECT_REQUEST = "DELETE_PROJECT_REQUEST";
export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";
export const DELETE_PROJECT_FAILURE = "DELETE_PROJECT_FAILURE";

export const CREATE_PROJECT_REQUEST = "CREATE_PROJECT_REQUEST";
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_FAILURE = "CREATE_PROJECT_FAILURE";

export const UPDATE_PROJECT_REQUEST = "UPDATE_PROJECT_REQUEST";
export const UPDATE_PROJECT_SUCCESS = "UPDATE_PROJECT_SUCCESS";
export const UPDATE_PROJECT_FAILURE = "UPDATE_PROJECT_FAILURE";

export const REMOVE_MEMBER_IN_PROJECT_REQUEST =
  "REMOVE_MEMBER_IN_PROJECT_REQUEST";
export const REMOVE_MEMBER_IN_PROJECT_SUCCESS =
  "REMOVE_MEMBER_IN_PROJECT_SUCCESS";
export const REMOVE_MEMBER_IN_PROJECT_FAILURE =
  "REMOVE_MEMBER_IN_PROJECT_FAILURE";

export const ADD_MEMBER_IN_PROJECT_REQUEST = "ADD_MEMBER_IN_PROJECT_REQUEST";
export const ADD_MEMBER_IN_PROJECT_SUCCESS = "ADD_MEMBER_IN_PROJECT_SUCCESS";
export const ADD_MEMBER_IN_PROJECT_FAILURE = "ADD_MEMBER_IN_PROJECT_FAILURE";
