export const GET_ALL_CHAT_REQUEST = "GET_ALL_CHAT_REQUEST";
export const GET_ALL_CHAT_SUCCESS = "GET_ALL_CHAT_SUCCESS";
export const GET_ALL_CHAT_FAILURE = "GET_ALL_CHAT_FAILURE";

export const CLEAR_MESSEAGE = "CLEAR_MESSEAGE";

export const GET_ALL_MESSAGE_REQUEST = "GET_ALL_MESSAGE_REQUEST";
export const GET_ALL_MESSAGE_SUCCESS = "GET_ALL_MESSAGE_SUCCESS";
export const GET_ALL_MESSAGE_FAILURE = "GET_ALL_MESSAGE_FAILURE";

export const CREATE_MESSAGE_REQUEST = "CREATE_MESSAGE_REQUEST";
export const CREATE_MESSAGE_SUCCESS = "CREATE_MESSAGE_SUCCESS";
export const CREATE_MESSAGE_FAILURE = "CREATE_MESSAGE_FAILURE";

export const ADD_MESSAGE_IN_ROOM_REQUEST = "ADD_MESSAGE_IN_ROOM_REQUEST";
export const ADD_MESSAGE_IN_ROOM_SUCCESS = "ADD_MESSAGE_IN_ROOM_SUCCESS";
export const ADD_MESSAGE_IN_ROOM_FAILURE = "ADD_MESSAGE_IN_ROOM_FAILURE";

export const EDIT_MESSAGE_IN_ROOM_REQUEST = "EDIT_MESSAGE_IN_ROOM_REQUEST";
export const EDIT_MESSAGE_IN_ROOM_SUCCESS = "EDIT_MESSAGE_IN_ROOM_SUCCESS";
export const EDIT_MESSAGE_IN_ROOM_FAILURE = "EDIT_MESSAGE_IN_ROOM_FAILURE";

export const DELETE_MESSAGE_IN_ROOM_REQUEST = "DELETE_MESSAGE_IN_ROOM_REQUEST";
export const DELETE_MESSAGE_IN_ROOM_SUCCESS = "DELETE_MESSAGE_IN_ROOM_SUCCESS";
export const DELETE_MESSAGE_IN_ROOM_FAILURE = "DELETE_MESSAGE_IN_ROOM_FAILURE";

export const CREATE_CHAT_REQUEST = "CREATE_CHAT_REQUEST";
export const CREATE_CHAT_SUCCESS = "CREATE_CHAT_SUCCESS";
export const CREATE_CHAT_FAILURE = "CREATE_CHAT_FAILURE";
